# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            suffix: intel
          - os: macos-latest
            suffix: arm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install GTK4
        run: brew install gtk4 gtksourceview5 libadwaita

      - uses: demarey/pharo-setup-gha@main
        with:
          version: 13

      - name: Run Pharo
        run: |
          $PHARO --headless Pharo.image eval "Metacello new repository: 'gitlocal://./src'; baseline: 'BundleBuilder'; load. (Smalltalk globals at: #MacBundleBuilder) makeGTK4Bundle${{ matrix.suffix == 'arm' && 'ARM' || '' }}"
          
          ls -R
          cp -R pharo-vm pharo-${{ matrix.suffix }}-vm
          cp gtk4/* pharo-${{ matrix.suffix }}-vm/Pharo.app/Contents/MacOS/Plugins/
          codesign --remove-signature pharo-${{ matrix.suffix }}-vm/Pharo.app
          codesign --force --deep --sign - pharo-${{ matrix.suffix }}-vm/Pharo.app

      - name: Archive VM
        uses: actions/upload-artifact@v4
        with:
          name: pharo-gtk4-${{ matrix.suffix }}-vm
          path: pharo-${{ matrix.suffix }}-vm/*.app

